Added content with 4 lessons
agorapp-dao/agorapp-solana pull request #3
Opened 2024-04-14 08:00 UTC by pkozelka

Added content, minor fixes and a tiny optimization.

Note that Lesson `transfer-tokens` is currently excluded, as it is not so important and so very relevant to basic level of the course.

Its code can be completed later if needed, or removed completely.

2024-04-15 06:31 UTC, romario333 requested changes

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
>  Work in progress
Remove Work in progress, looks good to me

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
> +https://careerbooster.teachable.com/courses/1869000/lectures/42811474 :
It's weird to start with the link without any explanation what is this link for. Also it does not work for me, even if I login and enroll, I get:

![CleanShot 2024-04-15 at 07 11 31](https://github.com/agorapp-dao/agorapp-solana/assets/373775/a6fd20ee-7d98-4811-b9ad-5acd60e2cd61)

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
> +Development of Solana contracts can be developed using one of these frameworks:
Remove `Development of`:

> Solana contracts can be developed using one of these frameworks

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
> +For instruction data, we use a raw byte array `[u8]` to represent the instruction data passed to the program.
`to represent the program's input data` would be more clear IMO. Instructions data evokes in me a list of instructions that should be executed.

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
> +It will be a simple program that produces text "Hello, Solana" in the logs.
Change to `Modify the program on the right to write a `Hello, Solana` text in the logs.` ?

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/cpi/lesson.md
> +Using a PDA, a program may be given the authority over an account and later transfer that authority to another program.
Add numbers to content directories (02-transfer-lamports, 03-cpi...)

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/transfer-lamports/lesson.md
> +A lamport is the smallest unit of time in Solana, and it is used to measure the cost of computational resources and storage on the Solana blockchain.
> A lamport is the smallest unit of time

Is this accurate? Is it really a unit of time?

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/transfer-lamports/lesson.md
> +If the account holds enough lamports, it can be marked as rent-exempt, meaning it does not need to pay rent to remain on the blockchain.
I don't understand this paragraph. So there are two ways how contract can be funded?

1. Locking lamports in program account

Are these lamports spent for something or do they stay in the account untouched?

2. Paying rent

How do you pay rent?

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/transfer-lamports/lesson.md
> +To avoid underflow or overflow errors, it ios recommended to set your `Cargo.toml` to use overflow checks.
typo: `it ios`

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/cpi/lesson.md
> +This is possible because the program can act as the signer in the transaction that gives authority.
I don't understand the role and importance of PDA from this text.

2024-04-15 06:31 UTC, romario333 commented on packages/content/solana/rust/intro-to-solana/public/cpi/lesson.md
> +Note that this returns a tuple with the derived address and the bump seed.
I don't understand this paragraph at all. Maybe too much information at this point?

2024-04-15 23:12 UTC, pkozelka commented on packages/content/solana/rust/intro-to-solana/public/01-introduction/lesson.md
> +https://careerbooster.teachable.com/courses/1869000/lectures/42811474 :
sorry it was just a note that I forgot to remove ;)

2024-04-17 13:08 UTC, romario333 approved these changes

2024-04-17 13:08 UTC, merged